title: Italian Summer Dreams
description: This is Lucia's ideal summer in Italy

remote_theme: pages-themes/slate@v0.2.0 # Establishes a theme
plugins:
- jekyll-remote-theme # tool used to build the github pages site
